### ISSUE TITLE
[BUG] Settings not saving properly.

### ISSUE THREAD

**Issue by Lombardi128** [aerisarn/gzdoom-uwp#3]
### Which game are you running with GZDoom?

None

### What Operating System are you using?

None

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

After talking with other people, it seems that it only saves settings sometimes. It doesn't matter if you quit from within the game or quit using the Xbox menu. It seems random whether or not it actually saves.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Start game
2. Change settings
3. Quit game

### Your configuration

```ini
Whatever the Free Look setting in the ini is called.
```

**Comment by aerisarn** [comment]
Expected Behavior as those settings are not flagged as CVAR_ARCHIVE by the engine. The implications of setting those as Archive are uncertain, but I'll follow the official release line.
Workaround and explanation available here
https://forum.zdoom.org/viewtopic.php?t=63560
